services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
