services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
    ports:
      - "80:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true